### ISSUE TITLE
Proteger master - Mejorar estructura del repo

### ISSUE THREAD

**Issue by cbuffevant** [DatosConcepcion/Concepcion-transparente#3]
Master se debería modificar solamente mediante pull requests. No commitear directamente.
Master debería representar lo que está en producción. Deberíamos tener feature branches y release branches.

**Comment by hectorh30** [comment]
Se configuraron las siguientes opciones de _Branch protection for master_:

- **Protect this branch**
- **Include administrators**

Con esto se obligará a integrar mediante pull requests los features y bugfixes.
